registration_key:
    admin: trust_me
    tour_owner: oke
mail:
    host: smtp.gmail.com
    password: aoljzwgou
    port: 587
    username: travelovecompany@gmail.com
oauth-google:
    access_type: offline
    client_id: 226555921335-sg9rdfbo4ulr28i2u8fqu.apps.googleusercontent.com
    client_secret: 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
    redirect_uri: http%3A%2F%2Flocalhost%3A8080%2Fauth%2Foauth%2Fgoogle
    scope: https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/userinfo.profile
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 261dfs220
        url: jdbc:mysql://localhost:3306/travelove
        username: root
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

    rabbitmq:
        host: rabbitmq
    file:
        name: log/dev.log

server:
    port: 2511
#    ssl:
#        key-store: data/keystore.p12
#        key-store-password: 26122002loc
#        keyStoreType: PKCS12
#        keyAlias: tomcat
#        enabled: true
##        certificate: data/certificate.crt
##        certificate-private-key: data/private.key
aws:
    region: ap-southeast-1
    s3:
        access_key: ${ACCESS}
        secret_key: ${SECRET}
        bucket_name: travelove-data

redis:
    host: ${REDIS_HOST}
    port: 6379

payment:
#    vnpay: http://localhost:5000/api/vnpay/create-payment
#    zalopay: http://localhost:5000/api/zalopay/create-payment
#    paypal: http://localhost:5000/api/paypal/create-payment

        vnpay: http://payment:5000/api/vnpay/create-payment
        zalopay: http://payment:5000/api/zalopay/create-payment
        paypal:  http://payment:5000/api/paypal/create-payment
oauth:
    google:
        host: https://www.travelovecompany.com
#        host: http://localhost:3000
web:
    host: https://www.travelovecompany.com


